language: c

sudo: false # required

os:
  - linux
#  - osx

compiler:
  - clang
  - gcc

matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
#  - if [ "$CC" = "gcc" ] ; then sudo apt-get install -qq gcc-5; fi
#  - if [ "$CXX" = "g++" ] ; then sudo apt-get install -qq g++-5; fi
  - if [ "$CC" = "gcc" ] ; then export CC="gcc-5" CC="gcc-5"; fi
  - if [ "$CXX" = "g++" ] ; then export CXX="g++-5" CC="g++-5"; fi
#  - ls -R /usr/bin | grep gcc
#  - gcc -v
#  - set
#  - export

branches:
  only:
    - master

script:
  - cmake . && make && ./test/testrun.sh
