language: c

sudo: required

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
  - if [ "$CC" = "gcc" ] ; then sudo apt-get install -qq g++-5.2; fi
  - if [ "$CC" = "gcc" ] ; then export CXX="g++-5.2" CC="gcc-5.2"; fi

branches:
  only:
    - master

script:
  - cmake .
  - make
  - ./test/testrun.sh
