# branches to build
branches:
  only:
    - master
    - develop

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: "C:\projects\spb-dialog-c\"

platform:
  - x64
  - x86

configuration: Debug

install: # by default, all script lines are interpreted as batch

build:
  project: ALL_BUILD.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - cmake -G "Visual Studio 14 2015 Win64" .

after_build:
  - DIR /S > "C:\projects\spb-dialog-c\listdir.log"
  - test\testrun.bat

artifacts:
  - path: "C:\projects\spb-dialog-c\listdir.log"
    name: ListDir
