environment:
  P: "c:/projects/libs"
  ACCOUNT:
      secure: F8Xu4syZJRRLmTnPDOUjr5bG7Lk6UburldIUuxZ/OJQ=

# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\sqlite

platform:
  - x86
  - x64

configuration: Debug

install:
  # by default, all script lines are interpreted as batch

build:
  project: INSTALL.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - cmake -G "Visual Studio 14 2015 Win64" .
